/**
 */
package work.andycarpenter.webgen.pims.webui.provider;

import java.util.ArrayList;
import java.util.Collection;
import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import work.andycarpenter.webgen.pims.webui.util.WebuiAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class WebuiItemProviderAdapterFactory extends WebuiAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public WebuiItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.WebUI} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WebUIItemProvider webUIItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.WebUI}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWebUIAdapter() {
		if (webUIItemProvider == null) {
			webUIItemProvider = new WebUIItemProvider(this);
		}

		return webUIItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.Navigation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NavigationItemProvider navigationItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.Navigation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNavigationAdapter() {
		if (navigationItemProvider == null) {
			navigationItemProvider = new NavigationItemProvider(this);
		}

		return navigationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.Menu} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MenuItemProvider menuItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.Menu}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMenuAdapter() {
		if (menuItemProvider == null) {
			menuItemProvider = new MenuItemProvider(this);
		}

		return menuItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.SubmenuEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubmenuEntryItemProvider submenuEntryItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.SubmenuEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubmenuEntryAdapter() {
		if (submenuEntryItemProvider == null) {
			submenuEntryItemProvider = new SubmenuEntryItemProvider(this);
		}

		return submenuEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.ActionMenuEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActionMenuEntryItemProvider actionMenuEntryItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.ActionMenuEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActionMenuEntryAdapter() {
		if (actionMenuEntryItemProvider == null) {
			actionMenuEntryItemProvider = new ActionMenuEntryItemProvider(this);
		}

		return actionMenuEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.EditStaticTextMenuEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EditStaticTextMenuEntryItemProvider editStaticTextMenuEntryItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.EditStaticTextMenuEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEditStaticTextMenuEntryAdapter() {
		if (editStaticTextMenuEntryItemProvider == null) {
			editStaticTextMenuEntryItemProvider = new EditStaticTextMenuEntryItemProvider(this);
		}

		return editStaticTextMenuEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.MenuFeature} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MenuFeatureItemProvider menuFeatureItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.MenuFeature}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMenuFeatureAdapter() {
		if (menuFeatureItemProvider == null) {
			menuFeatureItemProvider = new MenuFeatureItemProvider(this);
		}

		return menuFeatureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.DefaultUnitStyles} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DefaultUnitStylesItemProvider defaultUnitStylesItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.DefaultUnitStyles}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDefaultUnitStylesAdapter() {
		if (defaultUnitStylesItemProvider == null) {
			defaultUnitStylesItemProvider = new DefaultUnitStylesItemProvider(this);
		}

		return defaultUnitStylesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.CardsUnitStyles} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CardsUnitStylesItemProvider cardsUnitStylesItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.CardsUnitStyles}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCardsUnitStylesAdapter() {
		if (cardsUnitStylesItemProvider == null) {
			cardsUnitStylesItemProvider = new CardsUnitStylesItemProvider(this);
		}

		return cardsUnitStylesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.ImageCardsUnitStyles} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImageCardsUnitStylesItemProvider imageCardsUnitStylesItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.ImageCardsUnitStyles}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImageCardsUnitStylesAdapter() {
		if (imageCardsUnitStylesItemProvider == null) {
			imageCardsUnitStylesItemProvider = new ImageCardsUnitStylesItemProvider(this);
		}

		return imageCardsUnitStylesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.DetailsUnitStyles} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DetailsUnitStylesItemProvider detailsUnitStylesItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.DetailsUnitStyles}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDetailsUnitStylesAdapter() {
		if (detailsUnitStylesItemProvider == null) {
			detailsUnitStylesItemProvider = new DetailsUnitStylesItemProvider(this);
		}

		return detailsUnitStylesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.FormUnitStyles} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FormUnitStylesItemProvider formUnitStylesItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.FormUnitStyles}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFormUnitStylesAdapter() {
		if (formUnitStylesItemProvider == null) {
			formUnitStylesItemProvider = new FormUnitStylesItemProvider(this);
		}

		return formUnitStylesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.GalleryUnitStyles} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GalleryUnitStylesItemProvider galleryUnitStylesItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.GalleryUnitStyles}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGalleryUnitStylesAdapter() {
		if (galleryUnitStylesItemProvider == null) {
			galleryUnitStylesItemProvider = new GalleryUnitStylesItemProvider(this);
		}

		return galleryUnitStylesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.SliderUnitStyles} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SliderUnitStylesItemProvider sliderUnitStylesItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.SliderUnitStyles}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSliderUnitStylesAdapter() {
		if (sliderUnitStylesItemProvider == null) {
			sliderUnitStylesItemProvider = new SliderUnitStylesItemProvider(this);
		}

		return sliderUnitStylesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.StaticUnitStyles} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StaticUnitStylesItemProvider staticUnitStylesItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.StaticUnitStyles}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStaticUnitStylesAdapter() {
		if (staticUnitStylesItemProvider == null) {
			staticUnitStylesItemProvider = new StaticUnitStylesItemProvider(this);
		}

		return staticUnitStylesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.TabularUnitStyles} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TabularUnitStylesItemProvider tabularUnitStylesItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.TabularUnitStyles}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTabularUnitStylesAdapter() {
		if (tabularUnitStylesItemProvider == null) {
			tabularUnitStylesItemProvider = new TabularUnitStylesItemProvider(this);
		}

		return tabularUnitStylesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.ControllerLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ControllerLinkItemProvider controllerLinkItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.ControllerLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createControllerLinkAdapter() {
		if (controllerLinkItemProvider == null) {
			controllerLinkItemProvider = new ControllerLinkItemProvider(this);
		}

		return controllerLinkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.SinglePageController} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SinglePageControllerItemProvider singlePageControllerItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.SinglePageController}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSinglePageControllerAdapter() {
		if (singlePageControllerItemProvider == null) {
			singlePageControllerItemProvider = new SinglePageControllerItemProvider(this);
		}

		return singlePageControllerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.MultiPageController} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MultiPageControllerItemProvider multiPageControllerItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.MultiPageController}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMultiPageControllerAdapter() {
		if (multiPageControllerItemProvider == null) {
			multiPageControllerItemProvider = new MultiPageControllerItemProvider(this);
		}

		return multiPageControllerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.RouteActual} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RouteActualItemProvider routeActualItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.RouteActual}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRouteActualAdapter() {
		if (routeActualItemProvider == null) {
			routeActualItemProvider = new RouteActualItemProvider(this);
		}

		return routeActualItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.StaticUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StaticUnitItemProvider staticUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.StaticUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStaticUnitAdapter() {
		if (staticUnitItemProvider == null) {
			staticUnitItemProvider = new StaticUnitItemProvider(this);
		}

		return staticUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.CreateSitemapUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CreateSitemapUnitItemProvider createSitemapUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.CreateSitemapUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCreateSitemapUnitAdapter() {
		if (createSitemapUnitItemProvider == null) {
			createSitemapUnitItemProvider = new CreateSitemapUnitItemProvider(this);
		}

		return createSitemapUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.UnitElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnitElementItemProvider unitElementItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.UnitElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnitElementAdapter() {
		if (unitElementItemProvider == null) {
			unitElementItemProvider = new UnitElementItemProvider(this);
		}

		return unitElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.UnitResource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnitResourceItemProvider unitResourceItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.UnitResource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnitResourceAdapter() {
		if (unitResourceItemProvider == null) {
			unitResourceItemProvider = new UnitResourceItemProvider(this);
		}

		return unitResourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.UnitAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnitAssociationItemProvider unitAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.UnitAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnitAssociationAdapter() {
		if (unitAssociationItemProvider == null) {
			unitAssociationItemProvider = new UnitAssociationItemProvider(this);
		}

		return unitAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.UnitLabel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnitLabelItemProvider unitLabelItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.UnitLabel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnitLabelAdapter() {
		if (unitLabelItemProvider == null) {
			unitLabelItemProvider = new UnitLabelItemProvider(this);
		}

		return unitLabelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.DataTypeField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataTypeFieldItemProvider dataTypeFieldItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.DataTypeField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataTypeFieldAdapter() {
		if (dataTypeFieldItemProvider == null) {
			dataTypeFieldItemProvider = new DataTypeFieldItemProvider(this);
		}

		return dataTypeFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.DateField} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DateFieldItemProvider dateFieldItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.DateField}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDateFieldAdapter() {
		if (dateFieldItemProvider == null) {
			dateFieldItemProvider = new DateFieldItemProvider(this);
		}

		return dateFieldItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.ArrayFilter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ArrayFilterItemProvider arrayFilterItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.ArrayFilter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createArrayFilterAdapter() {
		if (arrayFilterItemProvider == null) {
			arrayFilterItemProvider = new ArrayFilterItemProvider(this);
		}

		return arrayFilterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.BooleanFilter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BooleanFilterItemProvider booleanFilterItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.BooleanFilter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBooleanFilterAdapter() {
		if (booleanFilterItemProvider == null) {
			booleanFilterItemProvider = new BooleanFilterItemProvider(this);
		}

		return booleanFilterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.ChoiceFilter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ChoiceFilterItemProvider choiceFilterItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.ChoiceFilter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createChoiceFilterAdapter() {
		if (choiceFilterItemProvider == null) {
			choiceFilterItemProvider = new ChoiceFilterItemProvider(this);
		}

		return choiceFilterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.ComparisionFilter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComparisionFilterItemProvider comparisionFilterItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.ComparisionFilter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createComparisionFilterAdapter() {
		if (comparisionFilterItemProvider == null) {
			comparisionFilterItemProvider = new ComparisionFilterItemProvider(this);
		}

		return comparisionFilterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.DateTimeFilter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DateTimeFilterItemProvider dateTimeFilterItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.DateTimeFilter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDateTimeFilterAdapter() {
		if (dateTimeFilterItemProvider == null) {
			dateTimeFilterItemProvider = new DateTimeFilterItemProvider(this);
		}

		return dateTimeFilterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.EntityFilter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityFilterItemProvider entityFilterItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.EntityFilter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityFilterAdapter() {
		if (entityFilterItemProvider == null) {
			entityFilterItemProvider = new EntityFilterItemProvider(this);
		}

		return entityFilterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.NullFilter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NullFilterItemProvider nullFilterItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.NullFilter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNullFilterAdapter() {
		if (nullFilterItemProvider == null) {
			nullFilterItemProvider = new NullFilterItemProvider(this);
		}

		return nullFilterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.NumericFilter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NumericFilterItemProvider numericFilterItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.NumericFilter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNumericFilterAdapter() {
		if (numericFilterItemProvider == null) {
			numericFilterItemProvider = new NumericFilterItemProvider(this);
		}

		return numericFilterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.TextFilter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextFilterItemProvider textFilterItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.TextFilter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTextFilterAdapter() {
		if (textFilterItemProvider == null) {
			textFilterItemProvider = new TextFilterItemProvider(this);
		}

		return textFilterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.CreateUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CreateUnitItemProvider createUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.CreateUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCreateUnitAdapter() {
		if (createUnitItemProvider == null) {
			createUnitItemProvider = new CreateUnitItemProvider(this);
		}

		return createUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.CreateUpdateUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CreateUpdateUnitItemProvider createUpdateUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.CreateUpdateUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCreateUpdateUnitAdapter() {
		if (createUpdateUnitItemProvider == null) {
			createUpdateUnitItemProvider = new CreateUpdateUnitItemProvider(this);
		}

		return createUpdateUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.UpdateUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UpdateUnitItemProvider updateUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.UpdateUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUpdateUnitAdapter() {
		if (updateUnitItemProvider == null) {
			updateUnitItemProvider = new UpdateUnitItemProvider(this);
		}

		return updateUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.MapUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MapUnitItemProvider mapUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.MapUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMapUnitAdapter() {
		if (mapUnitItemProvider == null) {
			mapUnitItemProvider = new MapUnitItemProvider(this);
		}

		return mapUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.DetailsUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DetailsUnitItemProvider detailsUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.DetailsUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDetailsUnitAdapter() {
		if (detailsUnitItemProvider == null) {
			detailsUnitItemProvider = new DetailsUnitItemProvider(this);
		}

		return detailsUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.TabularUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TabularUnitItemProvider tabularUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.TabularUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTabularUnitAdapter() {
		if (tabularUnitItemProvider == null) {
			tabularUnitItemProvider = new TabularUnitItemProvider(this);
		}

		return tabularUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.TextCardsUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextCardsUnitItemProvider textCardsUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.TextCardsUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTextCardsUnitAdapter() {
		if (textCardsUnitItemProvider == null) {
			textCardsUnitItemProvider = new TextCardsUnitItemProvider(this);
		}

		return textCardsUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.DateCardsUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DateCardsUnitItemProvider dateCardsUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.DateCardsUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDateCardsUnitAdapter() {
		if (dateCardsUnitItemProvider == null) {
			dateCardsUnitItemProvider = new DateCardsUnitItemProvider(this);
		}

		return dateCardsUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.ImageCardsUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImageCardsUnitItemProvider imageCardsUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.ImageCardsUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImageCardsUnitAdapter() {
		if (imageCardsUnitItemProvider == null) {
			imageCardsUnitItemProvider = new ImageCardsUnitItemProvider(this);
		}

		return imageCardsUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.SearchUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SearchUnitItemProvider searchUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.SearchUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSearchUnitAdapter() {
		if (searchUnitItemProvider == null) {
			searchUnitItemProvider = new SearchUnitItemProvider(this);
		}

		return searchUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.RegistrationUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RegistrationUnitItemProvider registrationUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.RegistrationUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRegistrationUnitAdapter() {
		if (registrationUnitItemProvider == null) {
			registrationUnitItemProvider = new RegistrationUnitItemProvider(this);
		}

		return registrationUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.LoginUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LoginUnitItemProvider loginUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.LoginUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLoginUnitAdapter() {
		if (loginUnitItemProvider == null) {
			loginUnitItemProvider = new LoginUnitItemProvider(this);
		}

		return loginUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.LogoutUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LogoutUnitItemProvider logoutUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.LogoutUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLogoutUnitAdapter() {
		if (logoutUnitItemProvider == null) {
			logoutUnitItemProvider = new LogoutUnitItemProvider(this);
		}

		return logoutUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.ForgottenPasswordUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ForgottenPasswordUnitItemProvider forgottenPasswordUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.ForgottenPasswordUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createForgottenPasswordUnitAdapter() {
		if (forgottenPasswordUnitItemProvider == null) {
			forgottenPasswordUnitItemProvider = new ForgottenPasswordUnitItemProvider(this);
		}

		return forgottenPasswordUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.ResetPasswordUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResetPasswordUnitItemProvider resetPasswordUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.ResetPasswordUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResetPasswordUnitAdapter() {
		if (resetPasswordUnitItemProvider == null) {
			resetPasswordUnitItemProvider = new ResetPasswordUnitItemProvider(this);
		}

		return resetPasswordUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.AssociationDisplayValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssociationDisplayValueItemProvider associationDisplayValueItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.AssociationDisplayValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAssociationDisplayValueAdapter() {
		if (associationDisplayValueItemProvider == null) {
			associationDisplayValueItemProvider = new AssociationDisplayValueItemProvider(this);
		}

		return associationDisplayValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.AttributeDisplayValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttributeDisplayValueItemProvider attributeDisplayValueItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.AttributeDisplayValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAttributeDisplayValueAdapter() {
		if (attributeDisplayValueItemProvider == null) {
			attributeDisplayValueItemProvider = new AttributeDisplayValueItemProvider(this);
		}

		return attributeDisplayValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.LabelDisplayValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LabelDisplayValueItemProvider labelDisplayValueItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.LabelDisplayValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLabelDisplayValueAdapter() {
		if (labelDisplayValueItemProvider == null) {
			labelDisplayValueItemProvider = new LabelDisplayValueItemProvider(this);
		}

		return labelDisplayValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.ResourceDisplayValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResourceDisplayValueItemProvider resourceDisplayValueItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.ResourceDisplayValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResourceDisplayValueAdapter() {
		if (resourceDisplayValueItemProvider == null) {
			resourceDisplayValueItemProvider = new ResourceDisplayValueItemProvider(this);
		}

		return resourceDisplayValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.SecurityAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SecurityActionItemProvider securityActionItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.SecurityAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSecurityActionAdapter() {
		if (securityActionItemProvider == null) {
			securityActionItemProvider = new SecurityActionItemProvider(this);
		}

		return securityActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.SliderUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SliderUnitItemProvider sliderUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.SliderUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSliderUnitAdapter() {
		if (sliderUnitItemProvider == null) {
			sliderUnitItemProvider = new SliderUnitItemProvider(this);
		}

		return sliderUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.GalleryUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GalleryUnitItemProvider galleryUnitItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.GalleryUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGalleryUnitAdapter() {
		if (galleryUnitItemProvider == null) {
			galleryUnitItemProvider = new GalleryUnitItemProvider(this);
		}

		return galleryUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.DeleteAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeleteActionItemProvider deleteActionItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.DeleteAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeleteActionAdapter() {
		if (deleteActionItemProvider == null) {
			deleteActionItemProvider = new DeleteActionItemProvider(this);
		}

		return deleteActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.ContainerSelectAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainerSelectActionItemProvider containerSelectActionItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.ContainerSelectAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainerSelectActionAdapter() {
		if (containerSelectActionItemProvider == null) {
			containerSelectActionItemProvider = new ContainerSelectActionItemProvider(this);
		}

		return containerSelectActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.InstanceSelectAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InstanceSelectActionItemProvider instanceSelectActionItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.InstanceSelectAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInstanceSelectActionAdapter() {
		if (instanceSelectActionItemProvider == null) {
			instanceSelectActionItemProvider = new InstanceSelectActionItemProvider(this);
		}

		return instanceSelectActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.TargetAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TargetActionItemProvider targetActionItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.TargetAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTargetActionAdapter() {
		if (targetActionItemProvider == null) {
			targetActionItemProvider = new TargetActionItemProvider(this);
		}

		return targetActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.InstanceOperationAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InstanceOperationActionItemProvider instanceOperationActionItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.InstanceOperationAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInstanceOperationActionAdapter() {
		if (instanceOperationActionItemProvider == null) {
			instanceOperationActionItemProvider = new InstanceOperationActionItemProvider(this);
		}

		return instanceOperationActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.ContainerOperationAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainerOperationActionItemProvider containerOperationActionItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.ContainerOperationAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainerOperationActionAdapter() {
		if (containerOperationActionItemProvider == null) {
			containerOperationActionItemProvider = new ContainerOperationActionItemProvider(this);
		}

		return containerOperationActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.GeneralOperationAction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GeneralOperationActionItemProvider generalOperationActionItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.GeneralOperationAction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGeneralOperationActionAdapter() {
		if (generalOperationActionItemProvider == null) {
			generalOperationActionItemProvider = new GeneralOperationActionItemProvider(this);
		}

		return generalOperationActionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.Message} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MessageItemProvider messageItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.Message}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMessageAdapter() {
		if (messageItemProvider == null) {
			messageItemProvider = new MessageItemProvider(this);
		}

		return messageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.webui.Badge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BadgeItemProvider badgeItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.webui.Badge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBadgeAdapter() {
		if (badgeItemProvider == null) {
			badgeItemProvider = new BadgeItemProvider(this);
		}

		return badgeItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

}
