<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="security" nsURI="http://andycarpenter.work/pim/security" nsPrefix="webgen-security">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Security">
    <eStructuralFeatures xsi:type="ecore:EReference" name="authentication" eType="#//Authentication"
        containment="true" eOpposite="#//Authentication/security"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Authentication" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="userKeyFromUser userKeyRequiredAttribute"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="userKeyFromUser" value="not user.oclIsUndefined() and not userKey.oclIsUndefined() implies&#xD;&#xA;&#x9;user.features->includes(userKey)"/>
      <details key="userKeyRequiredAttribute" value="not userKey.oclIsUndefined() implies&#xA;&#x9;userKey.cardinality = persistence::Cardinality::Required"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="security" lowerBound="1"
        eType="#//Security" eOpposite="#//Security/authentication"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" ordered="false" lowerBound="1"
        eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userKey" ordered="false"
        lowerBound="1" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitRegistrationName"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="registration"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitRegistrationUnitLabel"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Create Account"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitRegistrationActionLabel"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="Create Account"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitRegistrationConfirmLabel"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="Create Account"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitRegistrationUri"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="register"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitLoginName" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="login"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitLoginUnitLabel"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Login"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitLoginActionLabel"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="Login"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitLoginConfirmLabel"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="Login"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitLoginUri" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="login"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitLogoutName" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="logout"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitLogoutUnitLabel"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Logout"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitLogoutActionLabel"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="Logout"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitLogoutConfirmLabel"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="Logout"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitLogoutUri" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="logout"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitForgottenPasswordName"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="reset"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitForgottenPasswordUnitLabel"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Reset Password"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitForgottenPasswordActionLabel"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="Forgotten Password"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitForgottenPasswordConfirmLabel"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="Reset Password"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitForgottenPasswordUriRequest"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="reset-password"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitForgottenPasswordUriEmailSent"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="check-email"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitForgottenPasswordUriReset"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="reset"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implicitForgottenPasswordEmailSubject"
        ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Your password reset request"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AuthenticationKeyTypes">
    <eLiterals name="Any"/>
    <eLiterals name="Email" value="1"/>
    <eLiterals name="Username" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocalAuthenticationSystem" eSuperTypes="#//Authentication">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="captchaRequiresKeys"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="captchaRequiresKeys" value="-- useCaptcha implies not authenticates.captchaSiteKey.oclIsUndefined() and not authenticates.captchaSecretKey.oclIsUndefined()&#xD;&#xA;true"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authenticationModel" ordered="false"
        eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authenticationName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Authentication"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authenticationKey" lowerBound="1"
        eType="#//AuthenticationKeyTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resetPasswordRequestModel"
        eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resetPasswordRequestName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="ResetPasswordRequest"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registrationUnit" eType="#//SecurityUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loginUnit" eType="#//SecurityUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="logoutUnit" eType="#//SecurityUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forgottenPasswordUnit"
        eType="#//SecurityUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewRole" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="ROLE_SECURITY"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="editRole" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="ROLE_SECURITY"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useCaptcha" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowRememberMe" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowSelfRegistration"
        ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trackLoginAttempts" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useEmailActivation" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sendWelcomeEmail" ordered="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CasAuthentication" eSuperTypes="#//Authentication">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loginLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="login"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logoutLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="logout"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityUnit" abstract="true" interface="true"/>
</ecore:EPackage>
