<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="webui" nsURI="http://andycarpenter.work/pim/webui" nsPrefix="webgen_webui">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="webgen-base" value="platform:/resource/work.andycarpenter.webgen.pims.base/model/base.ecore#/"/>
    <details key="webgen-expression" value="platform:/resource/work.andycarpenter.webgen.pims.expression/model/expression.ecore#/"/>
    <details key="webgen-image" value="platform:/resource/work.andycarpenter.webgen.pims.image/model/image.ecore#/"/>
    <details key="webgen-persistence" value="platform:/resource/work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#/"/>
    <details key="webgen-security" value="platform:/resource/work.andycarpenter.webgen.pims.security/model/security.ecore#/"/>
    <details key="webgen-service" value="platform:/resource/work.andycarpenter.webgen.pims.service/model/service.ecore#/"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="WebUI">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="controllerNameUnique"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="controllerNameUnique" value="controllers->isUnique(name)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persistence" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Persistence"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="navigation" lowerBound="1"
        eType="#//Navigation" containment="true" eOpposite="#//Navigation/partOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.service/model/service.ecore#//Services"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controllers" upperBound="-1"
        eType="#//Controller" containment="true" eOpposite="#//Controller/webUI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useFormFloatingLabels"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultDateFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="jS F Y"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultTimeFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="G.i"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultDateTimeFormat"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="jS F Y G.i"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultCancelLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Cancel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultSaveLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Save"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultPageStyleClass"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultStyles" lowerBound="1"
        eType="#//DefaultUnitStyles" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultCardsStyles" lowerBound="1"
        eType="#//CardsUnitStyles" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultImageCardsStyles"
        lowerBound="1" eType="#//ImageCardsUnitStyles" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultDetailsStyles" lowerBound="1"
        eType="#//DetailsUnitStyles" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultFormStyles" lowerBound="1"
        eType="#//FormUnitStyles" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultGalleryStyles" lowerBound="1"
        eType="#//GalleryUnitStyles" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultSliderStyles" lowerBound="1"
        eType="#//SliderUnitStyles" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultStaticStyles" lowerBound="1"
        eType="#//StaticUnitStyles" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultTabularStyles" lowerBound="1"
        eType="#//TabularUnitStyles" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultMaximumUploadSize"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="2000000"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AuthenticationMenuPlacement">
    <eLiterals name="Above"/>
    <eLiterals name="Below" value="1"/>
    <eLiterals name="Integrated" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Navigation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="menuNameUnique"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="menuNameUnique" value="menus->isUnique(name)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partOf" lowerBound="1"
        eType="#//WebUI" eOpposite="#//WebUI/navigation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="menus" upperBound="-1"
        eType="#//Menu" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="navbarClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="navbar"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authenticationMenuPlacement"
        eType="#//AuthenticationMenuPlacement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="authenticationBarClass"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="nav"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Menu" eSuperTypes="../../work.andycarpenter.webgen.pims.base/model/base.ecore#//NamedDisplayElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//MenuEntry" containment="true" eOpposite="#//MenuEntry/partOf"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="omitCaption" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="captionClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="menu_caption"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="styleClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="menu"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="collapsible"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MenuEntry" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="partOf" lowerBound="1"
        eType="#//Menu" eOpposite="#//Menu/entries"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubmenuEntry" eSuperTypes="#//Menu #//MenuEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="authorisation" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.security/model/security.ecore#//AuthorisationExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alwaysVisible" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionMenuEntry" eSuperTypes="../../work.andycarpenter.webgen.pims.base/model/base.ecore#//NamedDisplayElement #//MenuEntry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="1"
        eType="#//ContentUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alwaysVisible" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditStaticTextMenuEntry" eSuperTypes="../../work.andycarpenter.webgen.pims.base/model/base.ecore#//NamedDisplayElement #//MenuEntry"/>
  <eClassifiers xsi:type="ecore:EClass" name="MenuFeature" eSuperTypes="#//MenuEntry"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContentUnitStyles" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sectionClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="captionClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contentClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicUnitStyles" abstract="true" eSuperTypes="#//ContentUnitStyles">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldListClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="definitionFieldListClass"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldLabelClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldValueClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionNavigationClass"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="anchorClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionUnitStyles" abstract="true"
      eSuperTypes="#//DynamicUnitStyles">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceControlClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceActionClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefaultUnitStyles" eSuperTypes="#//CollectionUnitStyles"/>
  <eClassifiers xsi:type="ecore:EClass" name="CardsUnitStyles" eSuperTypes="#//CollectionUnitStyles">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="card"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardHeaderClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="card-heder"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardBodyClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="card-body"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardFooterClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="card-footer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="badgeClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="badge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImageCardsUnitStyles" eSuperTypes="#//CardsUnitStyles">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageActionClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DetailsUnitStyles" eSuperTypes="#//DynamicUnitStyles"/>
  <eClassifiers xsi:type="ecore:EClass" name="FormUnitStyles" eSuperTypes="#//DynamicUnitStyles">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputGroupClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GalleryUnitStyles" eSuperTypes="#//CollectionUnitStyles"/>
  <eClassifiers xsi:type="ecore:EClass" name="SliderUnitStyles" eSuperTypes="#//CollectionUnitStyles"/>
  <eClassifiers xsi:type="ecore:EClass" name="StaticUnitStyles" eSuperTypes="#//ContentUnitStyles"/>
  <eClassifiers xsi:type="ecore:EClass" name="TabularUnitStyles" eSuperTypes="#//CollectionUnitStyles">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="headerClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="footerClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PageTopMenuOptions">
    <eLiterals name="NeverInclude"/>
    <eLiterals name="AlwaysInclude"/>
    <eLiterals name="IncludeWhenAuthenticated"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Controller" abstract="true" eSuperTypes="../../work.andycarpenter.webgen.pims.base/model/base.ecore#//NamedDisplayElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="contentUnitNameUniqueWithinController"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="contentUnitNameUniqueWithinController" value="units->isUnique(name)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="webUI" lowerBound="1" eType="#//WebUI"
        eOpposite="#//WebUI/controllers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentController" eType="#//ControllerLink"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childControllers" upperBound="-1"
        eType="#//ControllerLink" eOpposite="#//ControllerLink/targetController"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="units" upperBound="-1"
        eType="#//ContentUnit" containment="true" eOpposite="#//ContentUnit/controller"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uriElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="styleClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControllerLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetController" lowerBound="1"
        eType="#//Controller" eOpposite="#//Controller/childControllers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SinglePageController" eSuperTypes="#//Controller"/>
  <eClassifiers xsi:type="ecore:EClass" name="MultiPageController" eSuperTypes="#//Controller"/>
  <eClassifiers xsi:type="ecore:EClass" name="ContentUnit" abstract="true" eSuperTypes="../../work.andycarpenter.webgen.pims.base/model/base.ecore#//NamedDisplayElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controller" lowerBound="1"
        eType="#//Controller" eOpposite="#//Controller/units"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="createDefaultUriElement"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authorisation" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.security/model/security.ecore#//AuthorisationExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="purposeSummary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uriElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uriParent" eType="#//ContentUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alternative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localSectionClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="omitCaption" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localCaptionClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localContentClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticUnit" eSuperTypes="#//ContentUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateSitemapUnit" eSuperTypes="#//ContentUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deployedURL" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="sitemap.xml"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicUnit" abstract="true" eSuperTypes="#//ContentUnit #//ActionContainer ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//FeatureVariableContext">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="featuresMustBeFromContentType"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="featuresMustBeFromContentType" value="displayFields&#xA;&#x9;->select(f | f.oclIsKindOf(UnitFeature)).oclAsType(UnitFeature)&#xA;&#x9;->select(f | &#xA;&#x9;&#x9;if f.oclIsKindOf(UnitElement) then&#xA;&#x9;&#x9;&#x9;not f.oclAsType(UnitElement).attribute.oclIsUndefined()&#xA;&#x9;&#x9;else&#xA;&#x9;&#x9;&#x9;not f.oclAsType(UnitAssociation).association.oclIsUndefined()&#xA;&#x9;&#x9;endif)&#xA;&#x9;->forAll(f | &#xA;&#x9;&#x9;if f.oclIsKindOf(UnitElement) then&#xA;&#x9;&#x9;&#x9;contentType.allFeatures->includes(f.oclAsType(UnitElement).attribute)&#xA;&#x9;&#x9;else&#xA;&#x9;&#x9;&#x9;contentType.allFeatures->includes(f.oclAsType(UnitAssociation).association)&#xA;&#x9;&#x9;endif)"/>
    </eAnnotations>
    <eOperations name="containingType" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Entity"/>
    <eOperations name="referencableEntities" upperBound="-1" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentType" lowerBound="1"
        eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routeActuals" upperBound="-1"
        eType="#//RouteActual" containment="true" eOpposite="#//RouteActual/actualFor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayFields" upperBound="-1"
        eType="#//UnitField" containment="true" eOpposite="#//UnitField/displayedOn"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasWhenFieldsEmptyAddImplicitFields"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hideWhen" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.expression/model/expression.ecore#//Predicate"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="messageWhenHidden" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="header" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="footer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localFieldListClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localFieldLabelClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localFieldValueClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localControlClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localInstanceControlClass"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localAnchorClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localInstanceActionClass"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RouteActual">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualFor" lowerBound="1"
        eType="#//DynamicUnit" eOpposite="#//DynamicUnit/routeActuals"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routeParameter" lowerBound="1"
        eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.expression/model/expression.ecore#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CollectionDisplayOptions">
    <eLiterals name="LineDirection"/>
    <eLiterals name="PageDirection" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitField" abstract="true" eSuperTypes="../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//FeatureVariableContext">
    <eOperations name="referencableEntities" upperBound="-1" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayedOn" lowerBound="1"
        eType="#//DynamicUnit" eOpposite="#//DynamicUnit/displayFields"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authorisation" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.security/model/security.ecore#//AuthorisationExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hideWhen" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.expression/model/expression.ecore#//Predicate"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="help" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="escapeHTML" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collectionDisplayOption"
        eType="#//CollectionDisplayOptions" defaultValueLiteral="LineDirection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="truncate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disableInput" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localInputGroupClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localFieldLabelClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localFieldValueClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitFeature" abstract="true" eSuperTypes="#//UnitField ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Path #//ActionContainer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="atMostOneSelectAction noDeleteActions"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="atMostOneSelectAction" value="actions->select(a | a.oclIsKindOf(SelectAction))->size() &lt; 2"/>
      <details key="noDeleteActions" value="actions->select(a | a.oclIsKindOf(DeleteAction))->isEmpty()"/>
    </eAnnotations>
    <eOperations name="contextEntity" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="forcedValue" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.expression/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collectionUiAllowAdd" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collectionUiAllowRemove"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collectionMaximumValues"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultDisplayValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayDefaultWhen" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.expression/model/expression.ecore#//Predicate"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emptyCollectionDisplay"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="footer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autofocus" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitElement" eSuperTypes="#//UnitFeature ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//AttributePathElement">
    <eOperations name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.expression/model/expression.ecore#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obfuscateFormFields" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placeholder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationPattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitResource" eSuperTypes="#//UnitFeature ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//ResourcePathElement">
    <eOperations name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDeletable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDownloadable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showImageWhenEditing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imageFilter" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//ImageResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitAssociation" eSuperTypes="#//UnitFeature ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//AssociationPathElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="optionsValidChoice"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="optionsValidChoice" value="not options.oclIsUndefined() and not association.oclIsUndefined() implies&#xA;&#x9;displayedOn.controller.webUI.persistence.repositories&#xA;&#x9;&#x9;->select(r : persistence::Repository | r.serves = association.targetEntity)&#xA;&#x9;&#x9;->collect(r : persistence::Repository | r.selections)&#xA;&#x9;&#x9;->includes(options)"/>
    </eAnnotations>
    <eOperations name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Selection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="collectionSortBy" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useAutocomplete" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnitLabel" eSuperTypes="#//UnitField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" lowerBound="1" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//ModelLabel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="if label.oclIsUndefined() then&#xA;&#x9;''&#xA;else&#xA;&#x9;label.name&#xA;endif&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceField" abstract="true" eSuperTypes="../../work.andycarpenter.webgen.pims.base/model/base.ecore#//NamedDisplayElement #//UnitField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placeholder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationPattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repeatedField" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondDisplayLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondPlaceholder" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondHelp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypeField" eSuperTypes="#//InterfaceField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" lowerBound="1"
        eType="ecore:EClass ../../work.andycarpenter.webgen.pims.base/model/base.ecore#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="obfuscateFormFields" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encrypt" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interfaceType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DateField" eSuperTypes="#//InterfaceField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="details" lowerBound="1"
        eType="ecore:EEnum ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//DateDetails"
        defaultValueLiteral="DateOnly"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectableUnit" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingletonUnit" abstract="true" eSuperTypes="#//DynamicUnit">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="canOnlyTitleWithSingletons"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="canOnlyTitleWithSingletons" value="not title.oclIsUndefined() implies &#xA;&#x9;if title.oclIsKindOf(persistence::Attribute) then&#xA;&#x9;&#x9;title.oclAsType(persistence::Attribute).cardinality &lt;> persistence::Cardinality::Many&#xA;&#x9;else&#xA;&#x9;&#x9;true&#xA;&#x9;endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="title" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Label"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionUnit" abstract="true" eSuperTypes="#//DynamicUnit #//SelectableUnit #//ValueContext">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="canOnlyTitleWithSingletons selectionMustNotBeSingleton"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="canOnlyTitleWithSingletons" value="not unitTitle.oclIsUndefined() implies &#xA;&#x9;if unitTitle.oclIsKindOf(persistence::Attribute) then&#xA;&#x9;&#x9;unitTitle.oclAsType(persistence::Attribute).cardinality &lt;> persistence::Cardinality::Many&#xA;&#x9;else&#xA;&#x9;&#x9;true&#xA;&#x9;endif"/>
      <details key="selectionMustNotBeSingleton" value="not selection.oclIsUndefined() implies&#xA;&#x9;selection.limit &lt;> 1"/>
    </eAnnotations>
    <eOperations name="containingType" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Entity"/>
    <eOperations name="isContained" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="referencableEntities" upperBound="-1" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Entity"/>
    <eOperations name="valueEntities" upperBound="-1" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unitTitle" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Label"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementTitle" eType="#//DisplayValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="truncateElementTitle" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selection" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Selection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="findContainerSelection"
        eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Selection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="findElementSelection" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Selection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" upperBound="-1"
        eType="#//CollectionFilter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Filter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedFilters" upperBound="-1"
        eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Filter"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="omitFieldLabels" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultPaginationSize"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="10"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumPaginationSize"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emptyMessage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionFilter" abstract="true" eSuperTypes="../../work.andycarpenter.webgen.pims.base/model/base.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayFilter" eSuperTypes="#//CollectionFilter"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanFilter" eSuperTypes="#//CollectionFilter"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChoiceFilter" eSuperTypes="#//CollectionFilter"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComparisionFilter" eSuperTypes="#//CollectionFilter"/>
  <eClassifiers xsi:type="ecore:EClass" name="DateTimeFilter" eSuperTypes="#//CollectionFilter"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntityFilter" eSuperTypes="#//CollectionFilter"/>
  <eClassifiers xsi:type="ecore:EClass" name="NullFilter" eSuperTypes="#//CollectionFilter"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumericFilter" eSuperTypes="#//CollectionFilter"/>
  <eClassifiers xsi:type="ecore:EClass" name="TextFilter" eSuperTypes="#//CollectionFilter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" lowerBound="1"
        eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditUnit" abstract="true" eSuperTypes="#//SingletonUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useCaptcha" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="disableWhen" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.expression/model/expression.ecore#//Predicate"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="confirmDestination" eType="#//ContentUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="confirmLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="confirmMessage" eType="#//Message"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="successMessage" eType="#//Message"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cancelDestination" eType="#//ContentUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cancelLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unitInputGroupClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateUnit" eSuperTypes="#//EditUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="UpdateUnit" eSuperTypes="#//EditUnit #//SelectableUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onSaveContinueEditing"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayEmptyForm" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateUpdateUnit" eSuperTypes="#//EditUnit #//SelectableUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onSaveContinueEditing"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="updateUriElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clearLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapUnit" eSuperTypes="#//EditUnit #//SelectableUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readOnly" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultZoomLevel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="12"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//LocationAttribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="placeName" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DetailsUnit" eSuperTypes="#//SingletonUnit #//SelectableUnit">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="selectionMustBeSingleton selectionValidChoice"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="selectionMustBeSingleton" value="not selection.oclIsUndefined() implies&#xA;&#x9;selection.limit = 1"/>
      <details key="selectionValidChoice" value="not selection.oclIsUndefined() implies&#xA;&#x9;controller.webUI.persistence.repositories&#xA;&#x9;&#x9;->select(s : persistence::Repository | not s.serves.oclIsUndefined())&#xA;&#x9;&#x9;->select(s : persistence::Repository | contentType = s.serves)&#xA;&#x9;&#x9;->collect(s : persistence::Repository | s.selections)&#xA;&#x9;&#x9;->includes(selection)"/>
    </eAnnotations>
    <eOperations name="referencableEntities" upperBound="-1" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selection" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Selection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="omitFieldLabels" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TabularUnit" eSuperTypes="#//CollectionUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="headerClassOverride" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="footerClassOverride" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowClasses" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="odd_row,even_row"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CardsUnit" abstract="true" eSuperTypes="#//CollectionUnit ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//FeatureVariableContext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="badges" upperBound="-1"
        eType="#//Badge" containment="true" eOpposite="#//Badge/displayedOn"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="overlaySingleSelectAction"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localCardClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localCardHeaderClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localCardBodyClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localCardFooterClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localBadgeClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Badge" eSuperTypes="../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//FeatureVariableContext #//ValueContext">
    <eOperations name="referencableEntities" upperBound="-1" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Entity"/>
    <eOperations name="valueEntities" upperBound="-1" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayedOn" lowerBound="1"
        eType="#//CardsUnit" eOpposite="#//CardsUnit/badges"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//DisplayValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="title" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Attribute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayWhen" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.expression/model/expression.ecore#//Predicate"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localBadgeClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextCardsUnit" eSuperTypes="#//CardsUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="DateCardsUnit" eSuperTypes="#//CardsUnit #//ValueContext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementDate" lowerBound="1"
        eType="#//DisplayValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImageUnit" abstract="true" interface="true"
      eSuperTypes="#//ValueContext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="imagePathFeature" lowerBound="1"
        eType="#//DisplayValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="missingImagePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="showMissingImageWhen" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.expression/model/expression.ecore#//Predicate"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imageFilter" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.image/model/image.ecore#//ImageManipulation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImageCardsUnit" eSuperTypes="#//CardsUnit #//ImageUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="overlayTitle" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enableImageEnlargement"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revealUntruncatedContent"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageActionClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SliderUnit" eSuperTypes="#//CollectionUnit #//ImageUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitionTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GalleryUnit" eSuperTypes="#//CollectionUnit #//ImageUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fullSizeFilter" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.image/model/image.ecore#//ImageManipulation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitionTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlUnit" abstract="true" eSuperTypes="#//DynamicUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="submitLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cancelDestination" eType="#//Controller"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cancelLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SearchUnit" eSuperTypes="#//ControlUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultsDestination" lowerBound="1"
        eType="#//TabularUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegistrationUnit" eSuperTypes="#//EditUnit ../../work.andycarpenter.webgen.pims.security/model/security.ecore#//SecurityUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="LoginUnit" eSuperTypes="#//EditUnit ../../work.andycarpenter.webgen.pims.security/model/security.ecore#//SecurityUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="LogoutUnit" eSuperTypes="#//DynamicUnit ../../work.andycarpenter.webgen.pims.security/model/security.ecore#//SecurityUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForgottenPasswordUnit" eSuperTypes="#//EditUnit ../../work.andycarpenter.webgen.pims.security/model/security.ecore#//SecurityUnit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resetPasswordUnit" lowerBound="1"
        eType="#//ResetPasswordUnit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uriEmailSent" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emailSubject" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emailMessage" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emailSentCaption" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emailSentMessage" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResetPasswordUnit" eSuperTypes="#//EditUnit ../../work.andycarpenter.webgen.pims.security/model/security.ecore#//SecurityUnit"/>
  <eClassifiers xsi:type="ecore:EClass" name="ValueContext" abstract="true" interface="true">
    <eOperations name="valueEntities" upperBound="-1" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valueEntities" upperBound="-1"
        eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Entity"
        changeable="false" volatile="true" transient="true" unsettable="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="valueEntities()"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisplayValue" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationDisplayValue" eSuperTypes="../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//AssociationPathElement #//DisplayValue">
    <eOperations name="isSourceAssociation" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeDisplayValue" eSuperTypes="../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//AttributePathElement #//DisplayValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="LabelDisplayValue" eSuperTypes="#//DisplayValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="label" lowerBound="1" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//ModelLabel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" unsettable="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="if label.oclIsUndefined() then&#xA;&#x9;''&#xA;else&#xA;&#x9;label.name&#xA;endif"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceDisplayValue" eSuperTypes="../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//ResourcePathElement #//DisplayValue"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ContainerActionsPlacement">
    <eLiterals name="Above"/>
    <eLiterals name="Below" value="1"/>
    <eLiterals name="Float" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InstanceActionsPlacement">
    <eLiterals name="Footer"/>
    <eLiterals name="Float" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionContainer" abstract="true" interface="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="atMostOneDeleteAction"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="atMostOneDeleteAction" value="actions->select(a | a.oclIsKindOf(DeleteAction))->size() &lt; 2"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containerActionsPlacement"
        eType="#//ContainerActionsPlacement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instanceActionsPlacement"
        eType="#//InstanceActionsPlacement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//Action" containment="true" eOpposite="#//Action/usedBy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionNavigationClass"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=" "/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true" eSuperTypes="../../work.andycarpenter.webgen.pims.base/model/base.ecore#//NamedDisplayElement ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//FeatureVariableContext">
    <eOperations name="referencableEntities" upperBound="-1" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedBy" lowerBound="1"
        eType="#//ActionContainer" eOpposite="#//ActionContainer/actions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentUnit" eType="#//DynamicUnit"
        changeable="false" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="if usedBy.oclIsKindOf(DynamicUnit) then&#xA;&#x9;usedBy.oclAsType(DynamicUnit)&#xA;else if usedBy.oclIsKindOf(UnitFeature) then&#xA;&#x9;usedBy.oclAsType(UnitFeature).displayedOn&#xA;else&#xA;&#x9;null&#xA;endif endif"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayWhen" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.expression/model/expression.ecore#//Predicate"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enableWhen" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.expression/model/expression.ecore#//Predicate"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="confirmMessage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="successMessage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="failureMessage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disabledMessage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containingType" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//Entity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="derivation" value="if usedBy.oclIsKindOf(DynamicUnit) then&#xA;&#x9;usedBy.oclAsType(DynamicUnit).contentType&#xA;else if usedBy.oclIsKindOf(UnitFeature) then&#xA;&#x9;usedBy.oclAsType(UnitFeature).displayedOn.contentType&#xA;else&#xA;&#x9;null&#xA;endif endif"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SecurityAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass ../../work.andycarpenter.webgen.pims.security/model/security.ecore#//SecurityUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteAction" eSuperTypes="#//Action">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="canOnlyDeleteSingletons"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="canOnlyDeleteSingletons" value="if usedBy.oclIsKindOf(UnitElement) then&#xA;&#x9;usedBy.oclAsType(UnitElement).attribute.cardinality &lt;> persistence::Cardinality::Many&#xA;else if usedBy.oclIsKindOf(UnitAssociation) then&#xA;&#x9;usedBy.oclAsType(UnitAssociation).association.cardinality &lt;> persistence::Cardinality::Many&#xA;else&#xA;&#x9;usedBy.oclIsKindOf(CollectionUnit)&#xA;endif endif&#xA;"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authorisation" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.security/model/security.ecore#//AuthorisationExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uriElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectAction" abstract="true" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//SelectableUnit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="valuePath" eType="#//DisplayValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerSelectAction" eSuperTypes="#//SelectAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceSelectAction" eSuperTypes="#//SelectAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="TargetAction" eSuperTypes="#//SelectAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperationAction" abstract="true" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="ecore:EClass ../../work.andycarpenter.webgen.pims.service/model/service.ecore#//BusinessOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authorisation" eType="ecore:EClass ../../work.andycarpenter.webgen.pims.security/model/security.ecore#//AuthorisationExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uriElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerOperationAction" eSuperTypes="#//OperationAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceOperationAction" eSuperTypes="#//OperationAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralOperationAction" eSuperTypes="#//OperationAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Message" eSuperTypes="#//ValueContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="ecore:EClass ../../work.andycarpenter.webgen.pims.presistence/model/persistence.ecore#//FeatureVariable"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
