/**
 */
package work.andycarpenter.webgen.pims.persistence.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import work.andycarpenter.webgen.pims.persistence.util.PersistenceAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class PersistenceItemProviderAdapterFactory extends PersistenceAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public PersistenceItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.Persistence} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PersistenceItemProvider persistenceItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.Persistence}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPersistenceAdapter() {
		if (persistenceItemProvider == null) {
			persistenceItemProvider = new PersistenceItemProvider(this);
		}

		return persistenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.SerializationGroup} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SerializationGroupItemProvider serializationGroupItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.SerializationGroup}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSerializationGroupAdapter() {
		if (serializationGroupItemProvider == null) {
			serializationGroupItemProvider = new SerializationGroupItemProvider(this);
		}

		return serializationGroupItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.ModelLabel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelLabelItemProvider modelLabelItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.ModelLabel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelLabelAdapter() {
		if (modelLabelItemProvider == null) {
			modelLabelItemProvider = new ModelLabelItemProvider(this);
		}

		return modelLabelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.ModelLabelAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelLabelAttributeItemProvider modelLabelAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.ModelLabelAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelLabelAttributeAdapter() {
		if (modelLabelAttributeItemProvider == null) {
			modelLabelAttributeItemProvider = new ModelLabelAttributeItemProvider(this);
		}

		return modelLabelAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.ModelLabelAssociation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ModelLabelAssociationItemProvider modelLabelAssociationItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.ModelLabelAssociation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createModelLabelAssociationAdapter() {
		if (modelLabelAssociationItemProvider == null) {
			modelLabelAssociationItemProvider = new ModelLabelAssociationItemProvider(this);
		}

		return modelLabelAssociationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.Entity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EntityItemProvider entityItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.Entity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEntityAdapter() {
		if (entityItemProvider == null) {
			entityItemProvider = new EntityItemProvider(this);
		}

		return entityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.DataTypeAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataTypeAttributeItemProvider dataTypeAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.DataTypeAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataTypeAttributeAdapter() {
		if (dataTypeAttributeItemProvider == null) {
			dataTypeAttributeItemProvider = new DataTypeAttributeItemProvider(this);
		}

		return dataTypeAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.DateAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DateAttributeItemProvider dateAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.DateAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDateAttributeAdapter() {
		if (dateAttributeItemProvider == null) {
			dateAttributeItemProvider = new DateAttributeItemProvider(this);
		}

		return dateAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.UrlAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UrlAttributeItemProvider urlAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.UrlAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUrlAttributeAdapter() {
		if (urlAttributeItemProvider == null) {
			urlAttributeItemProvider = new UrlAttributeItemProvider(this);
		}

		return urlAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.StaticPathElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StaticPathElementItemProvider staticPathElementItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.StaticPathElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStaticPathElementAdapter() {
		if (staticPathElementItemProvider == null) {
			staticPathElementItemProvider = new StaticPathElementItemProvider(this);
		}

		return staticPathElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.DatePathElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DatePathElementItemProvider datePathElementItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.DatePathElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDatePathElementAdapter() {
		if (datePathElementItemProvider == null) {
			datePathElementItemProvider = new DatePathElementItemProvider(this);
		}

		return datePathElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.FileAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FileAttributeItemProvider fileAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.FileAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFileAttributeAdapter() {
		if (fileAttributeItemProvider == null) {
			fileAttributeItemProvider = new FileAttributeItemProvider(this);
		}

		return fileAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.ImageAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImageAttributeItemProvider imageAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.ImageAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImageAttributeAdapter() {
		if (imageAttributeItemProvider == null) {
			imageAttributeItemProvider = new ImageAttributeItemProvider(this);
		}

		return imageAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.LocationAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LocationAttributeItemProvider locationAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.LocationAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLocationAttributeAdapter() {
		if (locationAttributeItemProvider == null) {
			locationAttributeItemProvider = new LocationAttributeItemProvider(this);
		}

		return locationAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.AssociationWithoutContainment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssociationWithoutContainmentItemProvider associationWithoutContainmentItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.AssociationWithoutContainment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAssociationWithoutContainmentAdapter() {
		if (associationWithoutContainmentItemProvider == null) {
			associationWithoutContainmentItemProvider = new AssociationWithoutContainmentItemProvider(this);
		}

		return associationWithoutContainmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.AssociationWithContainment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssociationWithContainmentItemProvider associationWithContainmentItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.AssociationWithContainment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAssociationWithContainmentAdapter() {
		if (associationWithContainmentItemProvider == null) {
			associationWithContainmentItemProvider = new AssociationWithContainmentItemProvider(this);
		}

		return associationWithContainmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.AssociationKey} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssociationKeyItemProvider associationKeyItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.AssociationKey}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAssociationKeyAdapter() {
		if (associationKeyItemProvider == null) {
			associationKeyItemProvider = new AssociationKeyItemProvider(this);
		}

		return associationKeyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.Repository} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RepositoryItemProvider repositoryItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.Repository}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRepositoryAdapter() {
		if (repositoryItemProvider == null) {
			repositoryItemProvider = new RepositoryItemProvider(this);
		}

		return repositoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.Selection} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SelectionItemProvider selectionItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.Selection}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSelectionAdapter() {
		if (selectionItemProvider == null) {
			selectionItemProvider = new SelectionItemProvider(this);
		}

		return selectionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.Asc} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AscItemProvider ascItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.Asc}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAscAdapter() {
		if (ascItemProvider == null) {
			ascItemProvider = new AscItemProvider(this);
		}

		return ascItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.Desc} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DescItemProvider descItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.Desc}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDescAdapter() {
		if (descItemProvider == null) {
			descItemProvider = new DescItemProvider(this);
		}

		return descItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.Filter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FilterItemProvider filterItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.Filter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFilterAdapter() {
		if (filterItemProvider == null) {
			filterItemProvider = new FilterItemProvider(this);
		}

		return filterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link work.andycarpenter.webgen.pims.persistence.RepositoryFeatureReference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RepositoryFeatureReferenceItemProvider repositoryFeatureReferenceItemProvider;

	/**
	 * This creates an adapter for a {@link work.andycarpenter.webgen.pims.persistence.RepositoryFeatureReference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRepositoryFeatureReferenceAdapter() {
		if (repositoryFeatureReferenceItemProvider == null) {
			repositoryFeatureReferenceItemProvider = new RepositoryFeatureReferenceItemProvider(this);
		}

		return repositoryFeatureReferenceItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

}
